## 4회 기출 유형
- https://www.kaggle.com/datasets/agileteam/bigdatacertificationkr
- https://github.com/lovedlim/BigDataCertificationCourses

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## 문제 1.
- 주어진 리스트에 대해 아래 과정을 차례로 수행한 최종 결괏값을 출력하시오.
```[2, 3, 3.2, 5, 7.5, 10, 11.8, 12, 23, 25, 31.5, 34]```

- 제 1사분위수와 제 3사분위수를 구하시오.
- 제 1사분위수와 제 3사분위수 차이의 절댓값을 구하시오.
- 그 값의 소수점을 버린 후 정수로 출력하시오.

In [4]:
import numpy as np
lst = [2, 3, 3.2, 5, 7.5, 10, 11.8, 12, 23, 25, 31.5, 34]

a = np.quantile(lst, 0.25)
b = np.quantile(lst, 0.75)
print(a)
print(b)
print(abs(a - b))
print(int(abs(a - b)))

4.55
23.5
18.95
18

In [ ]:
import numpy as np
lst = [2, 3, 3.2, 5, 7.5, 10, 11.8, 12, 23, 25, 31.5, 34]
Q1 = np.quantile(lst, 0.25)
Q3 = np.quantile(lst, 0.75)

diff = abs(Q1-Q3)
result = int(diff)
print(result)

18

## 문제 2.
- 주어진 facebook 데이터 세트는 페이스북 라이브에 대한 사용자 반응을 집계한 것이다. 이 중 love 반응(num_loves)과 wow 반응(num_wows)을 매우 긍정적인 반응이라고 정의할 때, 전체 반응 수(num_reaction) 중 매우 긍정적인 반응 수가 차지하는 비율을 계산하시오. 그리고 그 비율이 0.5보다 작고, 0.4보다 크며 유형이 비디오에 해당하는 건수를 정수로 출력하시오.

In [9]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/빅분기 실기/빅데이터분석기사_실기_최종본/빅데이터분석기사_실기_최종본/작업장_제1유형/data/4회/402_facebook.csv")
df['ratio'] = (df['num_loves'] + df['num_wows']) / df['num_reactions']
df

cond = df.status_type == 'video'
df = df[cond]
df

cond = (df.ratio < 0.5) & (df.ratio > 0.4)
df = df[cond]
print(len(df))

90

In [ ]:
#  love 반응(num_loves)과 wow 반응(num_wows)을 매우 긍정적인 반응이라고 정의할 때,
# 전체 반응 수(num_reaction) 중 매우 긍정적인 반응 수가 차지하는 비율을 계산
df['pos_prop'] = (df['num_loves'] + df['num_wows']) / df['num_reactions']
df.head(1)

,status_id,status_type,num_reactions,num_comments,num_shares,num_likes,num_loves,num_wows,num_hahas,num_sads,num_angrys,pos_prop
0,246675545449582_1649696485147474,video,529,512,262,432,92,3,1,1,0,0.179584

In [ ]:
# 그리고 그 비율이 0.5보다 작고, 0.4보다 크며 유형이 비디오에 해당하는 건수를 정수로 출력하시오.
result = df.loc[(df['pos_prop'] < 0.5) & (df['pos_prop'] > 0.4) & (df['status_type'] == 'video')]
print(len(result))

90

## 문제 3.
- 주어진 netflix 데이터 세트는 넷플릭스에 등록된 컨텐츠의 메타 데이터이다. 2018년 1월에 넷플릭스에 등록된 컨텐츠 중에서 'United Kingdom'이 단독 제작한 컨텐츠의 수를 정수로 출력하시오.

### 방법 1.
- 날짜 데이터를 변환

In [33]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/빅분기 실기/빅데이터분석기사_실기_최종본/빅데이터분석기사_실기_최종본/작업장_제1유형/data/4회/403_netflix.csv")
df['date_added'] = df['date_added'].str.strip()
df['date_added'] = pd.to_datetime(df['date_added'])
cond = df['date_added'].dt.strftime('%Y-%m') == '2018-01'
df = df[cond]
cond = df['country'] == 'United Kingdom'
df = df[cond]
print(len(df))

6

In [19]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [20]:
df2 = df[df['country'] == "United Kingdom"].reset_index(drop=True)
df2.loc[:, 'date'] = pd.to_datetime(df2['date_added'])
df2.head(1)

ValueError: time data " December 15, 2018" doesn't match format "%B %d, %Y", at position 244. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
df2['year'] = df2['date'].dt.year
df2['month'] = df2['date'].dt.month
result = df2.loc[(df2['year'] == 2018.0) & (df2['month'] == 1.0)].reset_index(drop=True)
print(len(result))

6

### 방법 2
- contains 변환

In [12]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/빅분기 실기/빅데이터분석기사_실기_최종본/빅데이터분석기사_실기_최종본/작업장_제1유형/data/4회/403_netflix.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [ ]:
df2 = df[(df['date_added'].str.contains('January')) & (df['date_added'].str.contains('2018'))].reset_index(drop=True)
df2.head(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s5056,Movie,Expedition Happiness,Selima Taibi,"Selima Taibi, Felix Starck",Germany,"January 31, 2018",2017,TV-PG,96 min,"Documentaries, International Movies",A filmmaker and his musician girlfriend attemp...

In [ ]:
df2['country'].unique()

array(['Germany', 'United States', 'United Kingdom', 'Spain', 'Singapore',
       'Mexico', 'Argentina', 'Bulgaria, United States', 'South Korea',
       'Colombia', nan, 'United States, New Zealand', 'Japan',
       'Canada, United States', 'Soviet Union, India', 'India',
       'Australia, United Arab Emirates', 'Czech Republic, United States',
       'United Kingdom, United States', 'France',
       'United States, United Kingdom, France',
       'United States, India, Bangladesh', 'Germany, Belgium',
       'Canada, France, Italy, Morocco, United States', 'Nigeria',
       'United States, Canada', 'United States, Italy',
       'China, Hong Kong',
       'United Kingdom, United States, Dominican Republic',
       'India, France',
       'Denmark, Germany, Belgium, United Kingdom, France',
       'Brazil, India, China, United States', 'France, Belgium',
       'New Zealand', 'Ireland, Canada, United States, United Kingdom',
       'Thailand'], dtype=object)

In [ ]:
result = df2[df2['country'] == "United Kingdom"].reset_index(drop=True)
len(result)

6