## 당뇨병 여부 판단
- 이상치 처리 (Glucose, BloodPressure, SkinThickness, Insulin, BMI가 0인 값)

## [참고]작업형2 문구
- 출력을 원하실 경우 print() 함수 활용
- 예시) print(df.head())
- getcwd(), chdir() 등 작업 폴더 설정 불필요
- 파일 경로 상 내부 드라이브 경로(C: 등) 접근 불가

### 데이터 파일 읽기 예제
- import pandas as pd
- X_test = pd.read_csv("data/X_test.csv")
- X_train = pd.read_csv("data/X_train.csv")
- y_train = pd.read_csv("data/y_train.csv")

### 사용자 코딩

### 답안 제출 참고
- 아래 코드 예측변수와 수험번호를 개인별로 변경하여 활용
- pd.DataFrame({'cust_id': X_test.cust_id, 'gender': pred}).to_csv('003000000.csv', index=False)

In [2]:
# 시험환경 세팅 (코드 변경 X)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

def exam_data_load(df, target, id_name="", null_name=""):
    if id_name == "":
        df = df.reset_index().rename(columns={"index": "id"})
        id_name = 'id'
    else:
        id_name = id_name
    
    if null_name != "":
        df[df == null_name] = np.nan
    
    X_train, X_test = train_test_split(df, test_size=0.2, random_state=2021)
    
    y_train = X_train[[id_name, target]]
    X_train = X_train.drop(columns=[target])

    
    y_test = X_test[[id_name, target]]
    X_test = X_test.drop(columns=[target])
    return X_train, X_test, y_train, y_test 
    
df = pd.read_csv("../input/pima-indians-diabetes-database/diabetes.csv")
X_train, X_test, y_train, y_test = exam_data_load(df, target='Outcome')

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 9), (154, 9), (614, 2), (154, 2))

In [59]:
X_train, X_test, y_train, y_test = exam_data_load(df, target='Outcome')
# print(X_train.info())  # null 없음  전부 int, float
# print(X_test.info())   # null 없음  전부 int, float

# print(X_train.describe()) # id 없애 버릴 것 - y_train과 함께. 전부 스케일 해도 될 거 같음.
# print(X_test.describe())  # id 따로 빼놓을 것 - 전부 스케일 해도 될 거 같음.
# print(X_train.shape, y_train.shape, X_test.shape)
X_train = X_train.drop('id', axis = 1)
y_train = y_train.drop('id', axis = 1)
X_test_id = X_test.pop('id')
# print(X_train.shape, y_train.shape, X_test.shape)

del_index = X_train[X_train['Glucose'] == 0].index
X_train = X_train.drop(index=del_index, axis = 0)
y_train = y_train.drop(index=del_index, axis = 0)
# print(X_train.shape, y_train.shape, X_test.shape)
# cols = ['Pregnancies','BloodPressure', 'SkinThickness','Insulin', 'BMI']
# X_train[cols]
# X_test 

# 스케일링
cols = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()

X_train[cols] = scale.fit_transform(X_train[cols])
X_test[cols] = scale.transform(X_test[cols])

# 분할
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size = 0.15, random_state = 2024)
# print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)
# 모델링
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state = 2024, max_depth = 5)
clf = clf.fit(X_tr, y_tr)
pred = clf.predict(X_val)
pred

# 평가
from sklearn.metrics import accuracy_score
print(accuracy_score(y_val, pred))

# 예측
pred_test = clf.predict(X_test)

submit = pd.DataFrame({
    'cust_id' : X_test_id,
    'pred' : pred_test
}).to_csv('123.csv', index=False)
# 제출

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:38: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

0.7608695652173914

In [60]:

# 정확도 계산
print('test accuracy:', accuracy_score(y_test['Outcome'], pred_test))

test accuracy: 0.7662337662337663

In [61]:
y_test

      id  Outcome
258  258        0
220  220        1
438  438        0
130  130        1
730  730        1
..   ...      ...
678  678        1
500  500        0
256  256        0
80    80        0
174  174        0

[154 rows x 2 columns]

In [62]:
# 시험환경 세팅 (코드 변경 X)
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

def exam_data_load(df, target, id_name="", null_name=""):
    if id_name == "":
        df = df.reset_index().rename(columns={"index": "id"})
        id_name = 'id'
    else:
        id_name = id_name
    
    if null_name != "":
        df[df == null_name] = np.nan
    
    X_train, X_test = train_test_split(df, test_size=0.2, random_state=2021)
    
    y_train = X_train[[id_name, target]]
    X_train = X_train.drop(columns=[target])

    
    y_test = X_test[[id_name, target]]
    X_test = X_test.drop(columns=[target])
    return X_train, X_test, y_train, y_test 
    
df = pd.read_csv("../input/pima-indians-diabetes-database/diabetes.csv")
X_train, X_test, y_train, y_test = exam_data_load(df, target='Outcome')

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 9), (154, 9), (614, 2), (154, 2))

## Start

## 라이브러리 및 데이터 불러오기

In [63]:
# 라이브러리
import pandas as pd

In [64]:
# 데이터 불러오기 (생략)
X_train.shape, y_train.shape, X_test.shape

((614, 9), (614, 2), (154, 9))

## EDA

In [65]:
X_train.head()

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
147,147,2,106,64,35,119,30.5,1.400,34
344,344,8,95,72,0,0,36.8,0.485,57
390,390,1,100,66,29,196,32.0,0.444,42
150,150,1,136,74,50,204,37.4,0.399,24
132,132,3,170,64,37,225,34.5,0.356,30

In [66]:
y_train.value_counts()

id   Outcome
0    1          1
514  0          1
504  0          1
506  1          1
507  0          1
               ..
265  0          1
266  1          1
267  0          1
268  0          1
766  1          1
Length: 614, dtype: int64

In [67]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 614 entries, 147 to 116
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        614 non-null    int64
 1   Pregnancies               614 non-null    int64
 2   Glucose                   614 non-null    int64
 3   BloodPressure             614 non-null    int64
 4   SkinThickness             614 non-null    int64
 5   Insulin                   614 non-null    int64
 6   BMI                       614 non-null    float64
 7   DiabetesPedigreeFunction  614 non-null    float64
 8   Age                       614 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 48.0 KB

In [68]:
X_train.isnull().sum()

id                          0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [69]:
X_test.isnull().sum()

id                          0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64

In [70]:
X_train.describe()

,id,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
count,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000,614.000000
mean,386.978827,3.845277,120.705212,68.530945,20.982085,82.229642,31.948534,0.477471,33.319218
std,219.881344,3.388952,32.047977,19.761915,15.965031,116.525772,7.734385,0.339811,11.940953
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000
25%,196.500000,1.000000,99.000000,62.000000,0.000000,0.000000,27.400000,0.244250,24.000000
50%,388.000000,3.000000,117.000000,72.000000,23.000000,44.000000,32.250000,0.377000,29.000000
75%,575.750000,6.000000,140.000000,80.000000,33.000000,130.000000,36.600000,0.628500,41.000000
max,766.000000,17.000000,199.000000,114.000000,99.000000,846.000000,59.400000,2.420000,81.000000

## 데이터 전처리

In [71]:
#이상치 처리
#Train
print('Glucose:',len(X_train[X_train['Glucose']==0]))
print('BloodPressure:',len(X_train[X_train['BloodPressure']==0]))
print('SkinThickness:',len(X_train[X_train['SkinThickness']==0]))
print('Insulin:',len(X_train[X_train['Insulin']==0]))
print('BMI:',len(X_train[X_train['BMI']==0]))

Glucose: 5
BloodPressure: 31
SkinThickness: 175
Insulin: 287
BMI: 9

In [72]:
#Test
print('Glucose:',len(X_test[X_test['Glucose']==0]))
print('BloodPressure:',len(X_test[X_test['BloodPressure']==0]))
print('SkinThickness:',len(X_test[X_test['SkinThickness']==0]))
print('Insulin:',len(X_test[X_test['Insulin']==0]))
print('BMI:',len(X_test[X_test['BMI']==0]))

Glucose: 0
BloodPressure: 4
SkinThickness: 52
Insulin: 87
BMI: 2

트레인에만 0이 있는 포도당(Glucose)는 삭제
나머지는 평균값으로 대체 하여 이상치를 처리함

In [73]:
# 포도당 이상치 삭제
del_idx = X_train[(X_train['Glucose']==0)].index
del_idx

Int64Index([182, 75, 342, 502, 349], dtype='int64')

In [74]:
print('Glucose 이상치 삭제 전 :', X_train.shape, y_train.shape)
X_train = X_train.drop(index=del_idx, axis=0)
y_train = y_train.drop(index=del_idx, axis=0)
print('Glucose 이상치 삭제 후 :', X_train.shape, y_train.shape)

Glucose 이상치 삭제 전 : (614, 9) (614, 2)
Glucose 이상치 삭제 후 : (609, 9) (609, 2)

In [75]:
# 포도당을 제외한 이상치, 평균값으로 대체
cols = ['BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
cols_mean = X_train[cols].mean()
X_train.loc[:, cols].replace(0, cols_mean, inplace=True)
# 또는 X_train[cols] = X_train[cols].replace(0, cols_mean)

In [76]:
# 스케일링
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
cols = ['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']
X_train[cols] = scaler.fit_transform(X_train[cols])
X_test[cols] = scaler.fit_transform(X_test[cols])

In [77]:
# id 제외
X = X_train.drop('id',axis=1)
test = X_test.drop('id',axis=1)

In [78]:
from sklearn.svm import SVC
model = SVC(random_state=2022)
model.fit(X, y_train['Outcome'])
predictions = model.predict(test)

In [79]:
# 오버피팅 되었을 경우에 점수가 잘나올 수 있음 (객관적인 평가 아님, 밸리데이션 데이터로 평가 필요함)
round(model.score(X, y_train['Outcome']) * 100, 2)

83.42

In [80]:
output = pd.DataFrame({'idx': X_test.index, 'Outcome': predictions})
output.head()

   idx  Outcome
0  258        1
1  220        1
2  438        0
3  130        1
4  730        0

In [81]:
# 수험번호.csv로 출력
output.to_csv('1234567.csv', index=False)

## 결과 체점 (수험자는 알 수 없는 부분임)

In [82]:
round(model.score(test, y_test['Outcome']) * 100, 2) # 60점대로 낮은 정확도를 보여줌

76.62